[package]
name = "bip32_derivation"
version = "1.0.0"
authors = ["The Stratum V2 Developers"]
edition = "2021"
description = "bip32_derivation"
documentation = "https://docs.rs/bip32_derivation"
readme = "README.md"
homepage = "https://stratumprotocol.org"
repository = "https://github.com/stratum-mining/stratum"
license = "MIT OR Apache-2.0"
keywords = ["stratum", "mining", "bitcoin", "protocol"]

[lib]
name = "bip32_derivation"
path = "src/lib.rs"

[[bin]]
name = "bip32_derivation-bin"
path = "src/main.rs"

[dependencies]
stratum-common = { path = "../../common", version = "4.0.0" }


[dev-dependencies]
toml = { version = "0.5.6", git = "https://github.com/diondokter/toml-rs", default-features = false, rev = "c4161aa" }
