# This workflow is used to publish SV2 crates to crates.io
# the workflow tries to publish all the library crates by running scripts/release-libs.sh
# in case the `cargo publish` command fails, the script returns 1 and the entire workflow fails
# the only exception is when the `cargo publish` command fails because the crate has already
# been published, in which case the workflow continues

name: Release Libs

on:
  # Manually run by going to "Actions/Release" in Github and running the workflow
  workflow_dispatch:
  # every time a new release tag is created
  push:
    tags:
      - "v*.*.*"

jobs:
  libs_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.75.0
            override: true
      - name: Login
        run: cargo login ${{ secrets.CRATES_IO_DEPLOY_KEY }}

      # Base dependencies with no local dependencies
      - name: Publish crate config_helpers_sv2
        run: |
          ./scripts/release-libs.sh roles/roles-utils/config-helpers
          
      - name: Publish crate buffer_sv2
        run: |
          ./scripts/release-libs.sh utils/buffer

      - name: Publish crate error-handling
        run: |
          ./scripts/release-libs.sh utils/error-handling

      - name: Publish crate key-utils
        run: |
          ./scripts/release-libs.sh utils/key-utils

      - name: Publish crate noise_sv2
        run: |
          ./scripts/release-libs.sh protocols/v2/noise-sv2

      # binary_sv2 (depends on buffer_sv2)
      - name: Publish crate binary_sv2 codec
        run: |
          ./scripts/release-libs.sh protocols/v2/binary-sv2/codec

      - name: Publish crate binary_sv2 derive_codec
        run: |
          ./scripts/release-libs.sh protocols/v2/binary-sv2/derive_codec

      - name: Publish crate binary_sv2
        run: |
          ./scripts/release-libs.sh protocols/v2/binary-sv2

      # framing_sv2(depends on binary_sv2, buffer_sv2, noise_sv2)
      - name: Publish crate framing_sv2
        run: |
          ./scripts/release-libs.sh protocols/v2/framing-sv2

      # codec_sv2 (depends on framing_sv2, noise_sv2, binary_sv2, buffer_sv2, key-utils)
      - name: Publish crate codec_sv2
        run: |
          ./scripts/release-libs.sh protocols/v2/codec-sv2

      # Subprotocols (depend on binary_sv2)
      - name: Publish crate common_messages
        run: |
          ./scripts/release-libs.sh protocols/v2/subprotocols/common-messages

      - name: Publish crate job_declaration
        run: |
          ./scripts/release-libs.sh protocols/v2/subprotocols/job-declaration

      - name: Publish crate mining
        run: |
          ./scripts/release-libs.sh protocols/v2/subprotocols/mining

      - name: Publish crate template_distribution
        run: |
          ./scripts/release-libs.sh protocols/v2/subprotocols/template-distribution

      # channels_sv2 (depends on binary_sv2, common_messages_sv2, mining_sv2, template_distribution_sv2, job_declaration_sv2)
      - name: Publish crate channels_sv2
        run: |
          ./scripts/release-libs.sh protocols/v2/channels-sv2

      # parsers_sv2 (depends on binary_sv2, framing_sv2, common_messages, mining, template_distribution, job_declaration)
      - name: Publish crate parsers_sv2
        run: |
          ./scripts/release-libs.sh protocols/v2/parsers-sv2

      # sv1_api (depends on binary_sv2)
      - name: Publish crate v1
        run: |
          ./scripts/release-libs.sh protocols/v1

      # stratum_translation (depends on binary_sv2, mining_sv2, channels_sv2, v1)
      - name: Publish crate stratum_translation
        run: |
          ./scripts/release-libs.sh roles/roles-utils/stratum-translation

      # Roles logic (depends on codec_sv2 and subprotocols)
      - name: Publish crate roles_logic_sv2
        run: |
          ./scripts/release-libs.sh protocols/v2/roles-logic-sv2

      # Network helpers (depends on codec_sv2, sv1_api)
      - name: Publish crate network_helpers_sv2
        run: |
          ./scripts/release-libs.sh roles/roles-utils/network-helpers

      # Common (depends on roles_logic_sv2 and network_helpers_sv2)
      - name: Publish crate common
        run: |
          ./scripts/release-libs.sh common

      # handlers_sv2 (depends on parsers_sv2, binary_sv2, common_messages_sv2, mining_sv2, template_distribution_sv2, job_declaration_sv2)
      - name: Publish crate handlers_sv2
        run: |
          ./scripts/release-libs.sh protocols/v2/handlers-sv2

      # Utilities that depend on stratum-common
      - name: Publish crate bip32-key-derivation
        run: |
          ./scripts/release-libs.sh utils/bip32-key-derivation

      - name: Publish crate rpc_sv2
        run: |
          ./scripts/release-libs.sh roles/roles-utils/rpc