on:
  pull_request:
    branches:
      - main

name: MSRV 1.75 Check

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.75.0 # MSRV

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v1.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Build Benches
        run: cargo build --manifest-path=benches/Cargo.toml
      - name: Build Protocols
        run: cargo build --manifest-path=protocols/Cargo.toml
      - name: Build Roles
        run: cargo build --locked --manifest-path=roles/Cargo.toml
      - name: Build Utils
        run: cargo build --locked --manifest-path=utils/Cargo.toml
      - name: Build Integration Tests
        run: cargo build --locked --manifest-path=test/integration-tests/Cargo.toml

      # also check test compilation without running tests
      - name: Check Test Compilation for Benches
        run: cargo test --manifest-path=benches/Cargo.toml --no-run
      - name: Check Test Compilation for Protocols
        run: cargo test --manifest-path=protocols/Cargo.toml --no-run
      - name: Check Test Compilation for Roles
        run: cargo test --locked --manifest-path=roles/Cargo.toml --no-run
      - name: Check Test Compilation for Utils
        run: cargo test --locked --manifest-path=utils/Cargo.toml --no-run
      - name: Check Test Compilation for Integration Tests
        run: cargo test --locked --manifest-path=test/integration-tests/Cargo.toml --no-run
