on:
  pull_request:
    branches:
      - main

name: Test, Prop Tests, Example Tests

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-13
          - ubuntu-latest
        include:
          - os: macos-13
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - name: Install stable toolchain & components
        uses: actions/checkout@v4
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build
        run: |
          cargo build --manifest-path=benches/Cargo.toml
          cargo build --manifest-path=common/Cargo.toml
          cargo build --manifest-path=protocols/Cargo.toml
          cargo build --manifest-path=roles/Cargo.toml
          cargo build --manifest-path=utils/Cargo.toml
          cargo build --manifest-path=roles/roles-utils/config-helpers/Cargo.toml

      - name: Run sv1-client-and-server example
        run: |
          cargo run --manifest-path=protocols/v1/Cargo.toml --example client_and_server 30

      - name: Run framing-sv2 example
        run: |
          cargo run --manifest-path=protocols/v2/framing-sv2/Cargo.toml --example sv2_frame

      - name: Run codec-sv2 examples
        run: |
          cargo run --manifest-path=protocols/v2/codec-sv2/Cargo.toml --example unencrypted
          cargo run --manifest-path=protocols/v2/codec-sv2/Cargo.toml --example encrypted --features=noise_sv2

      - name: Run binary-sv2 examples
        run: |
          cargo run --manifest-path=protocols/v2/binary-sv2/Cargo.toml --example encode_decode

      - name: Run noise-sv2 examples
        run: |
          cargo run --manifest-path=protocols/v2/noise-sv2/Cargo.toml --example handshake

      - name: fuzz tests
        run: |
          if [ ${{ matrix.os }} == "ubuntu-latest" ]; then
            ./run.sh 30
          else
            echo "Skipping fuzz test on ${{ matrix.os }} - not supported"
          fi
        working-directory: utils/buffer/fuzz

      - name: Test
        run: |
          cargo test --manifest-path=benches/Cargo.toml
          cargo test --manifest-path=common/Cargo.toml
          cargo test --manifest-path=protocols/Cargo.toml
          cargo test --manifest-path=roles/Cargo.toml
          cargo test --manifest-path=utils/Cargo.toml
          cargo test --manifest-path=roles/roles-utils/config-helpers/Cargo.toml
          cargo test --manifest-path=roles/roles-utils/network-helpers/Cargo.toml sv1_connection::tests::test_sv1_connection --features sv1
          cargo test --manifest-path=roles/roles-utils/stratum-translation/Cargo.toml

      - name: Property based testing
        run: |
          cargo test --manifest-path=protocols/Cargo.toml --features prop_test

      - name: Run ping-pong-encrypted example
        run: |
          cargo run --manifest-path=examples/ping-pong-encrypted/Cargo.toml

      - name: Run ping-pong example
        run: |
          cargo run --manifest-path=examples/ping-pong/Cargo.toml
